# Example showing domain-specific prompt customization
dataset_system_prompt: "You are an expert in medical education and clinical practice."

# Medical topic generation: Clinical focus
topic_tree:
  topic_prompt: "Clinical diagnosis and treatment protocols"
  provider: "gemini"
  model: "gemini-2.5-flash-lite"
  temperature: 0.6  # Lower for medical accuracy
  degree: 3
  depth: 4
  # Medical topic exploration prompt
  topic_system_prompt: "You are a medical curriculum committee chair organizing clinical knowledge. Focus on evidence-based practices, differential diagnoses, standard protocols, and patient safety considerations. Ensure topics follow medical education standards and clinical workflows."
  save_as: "medical_topics.jsonl"

# Patient interaction data: Communication focused
data_engine:
  instructions: "Create realistic patient-doctor interactions with proper medical communication"
  provider: "gemini"
  model: "gemini-2.5-flash-lite"
  temperature: 0.7
  max_retries: 5
  # Patient communication specialist prompt
  generation_system_prompt: "You are a medical communication specialist and experienced physician. Create realistic patient interactions demonstrating empathetic bedside manner, clear medical explanations in patient-friendly language, proper informed consent discussions, and culturally sensitive care. Always prioritize patient safety and ethical considerations."

dataset:
  creation:
    num_steps: 50
    batch_size: 2
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    sys_msg: true
  save_as: "medical_communication_dataset.jsonl"