# Example showing specialized system prompts for different pipeline stages
dataset_system_prompt: "You are an AI assistant helping with educational content creation."

# Topic generation: Broad, exploratory thinking
topic_tree:
  topic_prompt: "Machine learning fundamentals for beginners"
  provider: "openai"
  model: "gpt-4"
  temperature: 0.8
  degree: 4
  depth: 3
  # Specialized prompt for topic exploration
  topic_system_prompt: "You are a curriculum designer creating comprehensive learning paths. Focus on logical progression, prerequisite relationships, and ensuring complete coverage of essential concepts. Think broadly about what learners need to know."
  save_as: "ml_topics.jsonl"

# Data generation: Detailed, pedagogical explanations
data_engine:
  instructions: "Create detailed explanations with practical examples"
  provider: "anthropic"
  model: "claude-3-opus"
  temperature: 0.7
  max_retries: 3
  # Specialized prompt for content creation
  generation_system_prompt: "You are an experienced machine learning instructor teaching beginners. Provide clear, step-by-step explanations with concrete examples, avoid jargon, include common misconceptions and how to avoid them. Always include practical code examples when relevant."

# Dataset creation
dataset:
  creation:
    num_steps: 20
    batch_size: 3
    provider: "openai"
    model: "gpt-4"
    sys_msg: true
  save_as: "ml_beginner_dataset.jsonl"