# Example configuration for topic graph generation
# System prompt should be specific to your domain and desired output style
dataset_system_prompt: "You are a senior software architect and computer science educator with 15+ years of experience. You provide comprehensive, technically accurate explanations with practical examples that demonstrate real-world applications. Your responses include concrete code samples, best practices, and common pitfalls to avoid."

# Topic graph configuration
topic_graph:
  topic_prompt: "Programming paradigms, languages, design patterns, data structures, architecture, algorithms, and their practical implementations across different programming languages with idiomatic specific examples"
  provider: "gemini"              # Optional: overrides the main provider
  model: "gemini-2.5-flash-lite"  # Optional: overrides the main model
  temperature: 0.7                # Temperature for generation (0.0-2.0)
  degree: 2                 # Number of subtopics per node
  depth: 2                  # Depth of the graph
  save_as: "programming_graph.json" # Where to save the graph

# Data engine configuration
data_engine:
  instructions: "Generate diverse programming examples"
  generation_system_prompt: "You are a senior software architect and computer science educator with 15+ years of experience. You provide comprehensive, technically accurate explanations with practical examples that demonstrate real-world applications. Your responses include concrete code samples, best practices, and common pitfalls to avoid."
  provider: "gemini"
  model: "gemini-2.5-flash-lite"
  temperature: 0.9
  max_retries: 3

# Dataset configuration
dataset:
  creation:
    num_steps: 4
    batch_size: 1
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    sys_msg: true
  save_as: "programming_dataset.jsonl"

# Optional: Hugging Face Hub configuration
# huggingface:
#   repository: "username/dataset-name"
#   tags: ["programming", "education", "synthetic"]
